apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.environment.SERVICE_NAME }}
  labels:
    app.kubernetes.io/name: {{ .Values.environment.SERVICE_NAME }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Values.environment.SERVICE_NAME }}
  template:
    metadata:
      labels:
        name: {{ .Values.environment.SERVICE_NAME }}
    spec:
      imagePullSecrets:
        - name: docker-secret
      containers:
        - name: {{ .Values.environment.SERVICE_NAME }}
          image: {{ .Values.environment.DOCKER_REPO }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Values.environment.SERVICE_NAME }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
