apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: { { .Values.environment.SERVICE_NAME } }
  namespace: { { .Values.environment.NAMESPACE } }
  labels:
    app.kubernetes.io/name: { { .Values.environment.SERVICE_NAME } }
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
    - hosts: [{ { .Values.environment.ENDPOINT } }]
      secretName: { { .Values.environment.INGRESS_SECRET_NAME } }
  rules:
    - host: { { .Values.environment.ENDPOINT } }
      http:
        paths:
          - path: /(/|$)(.*)
            backend:
              serviceName: { { .Values.environment.SERVICE_NAME } }
              servicePort: http
