apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.environment.SERVICE_NAME }}
  labels:
    app.kubernetes.io/name: {{ .Values.environment.SERVICE_NAME }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    name: {{ .Values.environment.SERVICE_NAME }}
