apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: #{SERVICE_NAME}#-#{NAMESPACE}#
  namespace: foundation
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: #{NAMESPACE}#
  source:
    repoURL: #{GIT_REPO}#
    targetRevision: "#{Build.SourceVersion}#"
    path: charts/#{SERVICE_NAME}#
    helm:
      parameters:
        # template variables
        - name: "image.tag"
          value: "#{Build.BuildNumber}#"
        - name: "environment.TZ"
          value: "#{TZ}#"
        - name: "environment.SERVICE_NAME"
          value: "#{SERVICE_NAME}#-#{NAMESPACE}#"
        - name: "environment.GIT_REPO"
          value: "#{GIT_REPO}#"
        - name: "environment.DOCKER_REPO"
          value: "#{DOCKER_REPO}#"
        - name: "environment.NAMESPACE"
          value: "#{NAMESPACE}#"
        # service variables
        - name: "replicaCount"
          value: "#{REPLICA_COUNT}#"
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: #{NAMESPACE}#

  # Sync policy
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
